pool:
  vmImage: ubuntu-latest

steps:
- script: |
    pip install --upgrade setuptools wheel
    pip install twine
    python setup.py sdist bdist_wheel
    twine upload --repository-url https://test.pypi.org/legacy/ dist/* -u $(username) -p $(password)
