version: 0.2

phases:
  install:
    runtime-versions:
        python: 3.8
  pre_build:
    commands:
       - pip install --upgrade setuptools wheel
       - pip install twine
       - python setup.py sdist bdist_wheel
       - twine upload --repository-url https://test.pypi.org/legacy/ dist/* -u $(username) -p $(password)
  build:
    commands:
      - echo Build started on `date`
      
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - python-package/setup.py 
Important
