version: 0.2

phases:
  install:
    runtime-versions:
       ubuntu-latest
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - pip install --upgrade setuptools wheel
        pip install twine
        python setup.py sdist bdist_wheel
        twine upload --repository-url https://test.pypi.org/legacy/ dist/* -u $(username) -p $(password)
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - python-package/setup.py 
Important
